### ISSUE TITLE
Hijri date according to JAKIM

### ISSUE THREAD

**Issue by khalid-hussain** [MalaysiaPrayerTimes/android#47]
السلام عليكم و رحمة الله و بركاته

I enjoy this app and love the updates. Great job.

I recently realized that the Hijri date it was providing was incorrect. However, I found the Hijri offset option under the app settings.

But I thought: since this app is for Malaysian prayer times, would it not be better to offer a JAKIM sync option so that the Hijri calendar is in accordance with JAKIM?

**Comment by i906** [comment]
Yes. I have checked at www.e-solat.gov.my but it seemed they do not provide any Hijri dates there.

Since there are no hijri date information there, this feature is not able to be developed at the moment.
