### ISSUE TITLE
How to Import your project to Android studio 

### ISSUE THREAD

**Issue by daskinder** [MalaysiaPrayerTimes/android#48]
please could you help me to import your projekt to android studio

**Comment by i906** [comment]
1. Open Android Studio
2. Check out project from Version Control > Git
3. Paste `https://github.com/MalaysiaPrayerTimes/android.git` into Git Repository URL
4. Clone
5. Press OK or yes for the next several dialogs
6. Wait for stuffs to be downloaded, indexed, etc.
7. Start coding

**Comment by daskinder** [comment]
thanks, how i can run it . sorry for my noob question

**Comment by i906** [comment]
1. Select `betaDebug` for `app` module and `debug` for `mpt-extension` module.
![as-1](https://cloud.githubusercontent.com/assets/866735/22148735/c8a96232-df4a-11e6-93d4-cd0a25c4e6dc.PNG)

2. Press Run
![as-2](https://cloud.githubusercontent.com/assets/866735/22148741/d0eee98a-df4a-11e6-8708-7a2c117a77c3.PNG)

3. Select device
![as-3](https://cloud.githubusercontent.com/assets/866735/22148755/ea6c6770-df4a-11e6-9c79-6ac3500c9ddf.PNG)
